### PR TITLE
Feature/issue 131

### PR DESCRIPTION
**Pull request by ronnie173**
Removed redundant react-notifications-system and react-redux-notification-system and added blueprint notifications

### CODE REVIEW

**Comment by ronnie173** [comment]
IDK if I did this right so let me know if I did anything wrong. Thanks

**Comment by Amazing-Space-Invader** [comment]
Something went wrong with [Travis](https://travis-ci.org/secret-tech/frontend-ico-dashboard/builds/364361694?utm_source=github_status&utm_medium=notification). I think CSS-loader runs twice.
```
Bundle generated with following warnings: 
./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--2-0!./node_modules/style-loader!./node_modules/css-loader??ref--2-2!./node_modules/normalize.css/normalize.css
Module build failed: Syntax Error 
(1:1) Unknown word
> 1 | // removed by extract-text-webpack-plugin
    | ^
 @ ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--2-0!./node_modules/style-loader!./node_modules/css-loader??ref--2-2!./node_modules/normalize.css/normalize.css
 @ ./node_modules/normalize.css/normalize.css
 @ ./src/index.js
 @ multi babel-polyfill ./src/index
./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--2-0!./node_modules/style-loader!./node_modules/css-loader??ref--2-2!./node_modules/normalize.css/normalize.css
Module build failed: Syntax Error 
(5:1) Unknown word
  3 | // load the styles
  4 | var content = require("!!../css-loader/index.js??ref--2-2!./normalize.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
 @ ./node_modules/normalize.css/normalize.css 4:14-230
 @ ./src/index.js
 @ multi babel-polyfill ./src/index
Done in 37.37s.
```

To remove dependency run `yarn remove react-notifications-system`. [This row](https://github.com/secret-tech/frontend-ico-dashboard/blob/develop/src/redux/rootReducer.js#L3) are deprecated. Try to remove dep from yarn and re-install all deps `rm -rf ./node_modules && yarn` and run the project. you will see errors that lack remote dependency. You need to delete all the code that used them. Also you can try find in `project/src` all `react-notifications-system` rows.

**Comment by ronnie173** [comment]
This is something wrong with a node module. I have done what you said to do and still it is getting that error.

**Comment by ronnie173** [comment]
Also I didn't touch any css at all

**Comment by Amazing-Space-Invader** [comment]
@ronnie173 thank you, all looks like good. We are fix Travis little bit later and merge it 👍

**Pull request merged**
